
title: NNL
baseurl: ""
url: "/"
markdown: kramdown
theme: alembic-jekyll-theme
#remote_theme: daviddarnes/alembic
#remote_theme: pages-themes/primer
#remote_theme: vinitkumar/white-paper
repository: neonailol/kactoos
#theme: minima
#theme: jekyll-theme-minimal
